export enum ActionTypes {
    GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS",
    GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES",
    CREATE_PRODUCT = "CREATE_PRODUCT",
    GET_ALL_USERS = "GET_ALL_USERS",
    SEARCH_PRODUCT = "SEARCH_PRODUCT",
    DELETE_PRODUCT = "DELETE_PRODUCT",
    UPDATE_PRODUCT = "UPDATE_PRODUCT",
    LOGIN = "LOGIN",
    LOGOUT = "LOGOUT",
    REGISTER = "REGISTER",
    ADD_TO_CART = "ADD_TO_CART",
    REMOVE_FROM_CART = "REMOVE_FROM_CART",
    ADD_FAVORITE = "ADD_FAVORITE",
    REMOVE_FAVORITE = "REMOVE_FAVORITE",
    
    
  }