"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ActionTypes = void 0;
var ActionTypes;
(function (ActionTypes) {
    ActionTypes["GET_ALL_PRODUCTS"] = "GET_ALL_PRODUCTS";
    ActionTypes["GET_ALL_CATEGORIES"] = "GET_ALL_CATEGORIES";
    ActionTypes["CREATE_PRODUCT"] = "CREATE_PRODUCT";
    ActionTypes["GET_ALL_USERS"] = "GET_ALL_USERS";
    ActionTypes["SEARCH_PRODUCT"] = "SEARCH_PRODUCT";
    ActionTypes["DELETE_PRODUCT"] = "DELETE_PRODUCT";
    ActionTypes["UPDATE_PRODUCT"] = "UPDATE_PRODUCT";
    ActionTypes["LOGIN"] = "LOGIN";
    ActionTypes["LOGOUT"] = "LOGOUT";
    ActionTypes["REGISTER"] = "REGISTER";
    ActionTypes["ADD_TO_CART"] = "ADD_TO_CART";
    ActionTypes["REMOVE_FROM_CART"] = "REMOVE_FROM_CART";
    ActionTypes["ADD_FAVORITE"] = "ADD_FAVORITE";
    ActionTypes["REMOVE_FAVORITE"] = "REMOVE_FAVORITE";
})(ActionTypes = exports.ActionTypes || (exports.ActionTypes = {}));
